/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("demo.kotlin-application-conventions")
    id("com.bmuschko.docker-remote-api") version "7.1.0"
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
}

application {
    // Define the main class for the application.
    mainClass.set("demo.app.AppKt")
}

tasks.create("locateJna") {
    doLast {
        val clazz = Class.forName("com.sun.jna.Native")
        val source = clazz.protectionDomain.codeSource

        println("Class $clazz was loaded from $source")
    }
}