/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    `kotlin-dsl`
}

repositories {
    // Use the plugin portal to apply community plugins in convention plugins.
    gradlePluginPortal()
}

dependencies {
    // changed this to use version 1.6.0
    // this pulls in net.java.dev.jna:jna:5.6.0
    implementation("org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.0")
}
